version: "2"
services:
  nfs:
    image: edtasixm06/nfs19:pam
    container_name: nfs
    hostname: nfs
    volumes:
      - "homes:/tmp/home"
        #    ports:
        #- "111:111"
        #- "2049:2049"
    privileged: true
    networks:
     - mynet
networks:
  mynet:
volumes:
  homes:
