version: "3"
services:
  ldap:
    image: edtasixm06/ldapserver19:latest
    container_name: ldap.edt.org
    hostname: ldap.edt.org
    ports: 
      - "389:389"
    networks:
      - mynet
networks:
  mynet:

