version: "3"
services:
  phpldapadmin:
    image: edtasixm06/phpldapadmin:19
    container_name: phpldapadmin.edt.org
    hostname: phpldapadmin.edt.org
    ports:
      - "80:80"
    networks:
      - mynet
networks:
  mynet:

